#!/bin/bash
 mv target/af-0.0.1-SNAPSHOT.jar target/af.jar
 gcloud compute scp target/af.jar alinso@afserver2:/tmp/
 gcloud compute ssh alinso@afserver2 --zone=europe-west4-a << EOF
 sudo service af stop
 cd /opt/af/
 rm  af.jar
 mv /tmp/af.jar /opt/af/
 sudo service af start
EOF