package com.alinso.myapp.entity.enums;

public enum NotificationType {
    MESSAGE,REQUEST,REQUEST_APPROVAL,REVIEW, FOLLOW,GENERAL, MEETING_COMMENT_AVAILABLE,MESSAGE_ACTIVITY,INVITATION,GHOST_MESSAGE,NEW_ACTIVITY,REMINDER
}
