package com.alinso.myapp.entity.enums;

public enum NotificationType {
    MESSAGE,REQUEST,REQUEST_APPROVAL,REVIEW, FOLLOW,GENERAL, MEETING_COMMENT_AVAILABLE,MESSAGE_EVENT,INVITATION,MESSAGE_WALL,NEW_EVENT,REMINDER
}
